Add check to ensure src directory is empty before proceeding with bin/download

diff --git a/compose/bin/download b/compose/bin/download
--- a/compose/bin/download
+++ b/compose/bin/download
@@ -9,7 +9,10 @@ BLUE='\033[0;34m'
 NC='\033[0m' # No Color
 
 if [ -d "./src" ]; then
-  echo "Error: The \"src\" directory is not empty. Please remove all contents within this directory and try again."
+  if [ "$(ls -A ./src)" ]; then
+    echo "Error: The \"src\" directory is not empty. Please remove all contents within this directory and try again."
+    exit 1
+  fi
   exit 1
 fi
 
