Added one liner command to install Magento using bin/download

diff --git a/compose/bin/download b/compose/bin/download
--- a/compose/bin/download
+++ b/compose/bin/download
@@ -15,32 +15,32 @@ if [ -d "./src" ]; then
   fi
 fi
 
-bin/stop
 
-bin/start --no-dev
-bin/stop sftp
-[ $? != 0 ] && echo "Failed to start Docker services" && exit
-
-bin/setup-composer-auth
-
-bin/fixowns
+echo "Downloading $EDITION version $VERSION"
 
 if [ "$EDITION" == "mageos-nightly" ]; then
-  bin/clinotty composer create-project --stability alpha --repository-url=https://upstream-nightly.mage-os.org magento/project-community-edition .
+  composer create-project --stability alpha --repository-url=https://upstream-nightly.mage-os.org magento/project-community-edition ./src
 elif [ "$EDITION" == "mageos-mirror" ] || [ "$EDITION" == "mageos" ]; then
-  bin/clinotty composer create-project --repository-url=https://mirror.mage-os.org magento/project-community-edition="${VERSION}" .
+  composer create-project --repository-url=https://mirror.mage-os.org magento/project-community-edition="${VERSION}" ./src
 elif [ "$EDITION" == "mageos-hypernode-mirror" ]; then
-  bin/clinotty composer create-project --repository-url=https://mage-os.hypernode.com/mirror magento/project-community-edition="${VERSION}" .
+  composer create-project --repository-url=https://mage-os.hypernode.com/mirror magento/project-community-edition="${VERSION}" ./src
 elif [ "$EDITION" == "mageos-maxcluster-mirror" ]; then
-  bin/clinotty composer create-project --repository-url=https://mage-os.maxcluster.net/mirror magento/project-community-edition="${VERSION}" .
+  composer create-project --repository-url=https://mage-os.maxcluster.net/mirror magento/project-community-edition="${VERSION}" ./src
 else
-  bin/clinotty composer create-project --repository=https://repo.magento.com/ magento/project-"${EDITION}"-edition="${VERSION}" .
+  composer create-project --repository=https://repo.magento.com/ magento/project-"${EDITION}"-edition="${VERSION}" ./src
 fi
 
-if [ $? != 0 ]; then
-    echo -e "${BLUE}Please check the installation guide at ${YELLOW}https://github.com/markshust/docker-magento#install-fails-because-project-directory-is-not-empty${BLUE} for troubleshooting.${NC}"
-else
-    bin/clinotty [ ! -f "./var/composer_home/auth.json" ] && bin/clinotty mkdir -p ./var/composer_home && bin/clinotty cp /var/www/.composer/auth.json ./var/composer_home/auth.json
-fi
+#if [ $? != 0 ]; then
+#    echo -e "${BLUE}Please check the installation guide at ${YELLOW}https://github.com/markshust/docker-magento#install-fails-because-project-directory-is-not-empty${BLUE} for troubleshooting.${NC}"
+#else
+#    bin/clinotty [ ! -f "./var/composer_home/auth.json" ] && bin/clinotty mkdir -p ./var/composer_home && bin/clinotty cp /var/www/.composer/auth.json ./var/composer_home/auth.json
+#fi
 
-bin/start --no-dev sftp
+# Remove the directories to avoid copying unnecessary files during docker build
+rm -rf src/vendor
+rm -rf src/app
+
+#
+#bin/setup -m -v 2.4.6-php8.1 -n
+
+echo "Done!"
diff --git a/compose/bin/setup b/compose/bin/setup
--- a/compose/bin/setup
+++ b/compose/bin/setup
@@ -1,43 +1,49 @@
 #!/usr/bin/env bash
 set -o errexit
 
-help()
-{
-   # Display Help
-   echo "Prepare docker setup for project."
-   echo
-   echo "Syntax: [domain (optional parameter, by default www.magento.local)] [-m]"
-   echo "options:"
-   echo "h     Print this Help."
-   echo "m     Prepare environment for macOS."
-   echo "v     Specify Magento version for compose file (e.g., 2.3.3, 2.3.7, latest)"
-   echo
+help() {
+    # Display Help
+    echo "Prepare docker setup for project."
+    echo
+    echo "Syntax: [domain (optional parameter, by default www.magento.local)] [-m] [-n]"
+    echo "options:"
+    echo "h     Print this Help."
+    echo "m     Prepare environment for macOS."
+    echo "n     Perform a new setup after using bin/download to initialize ./src with a new Magento project."
+    echo "v     Specify Magento version for compose file (e.g., 2.3.3, 2.3.7, 2.4.6-php8.1, latest)"
+    echo
 }
 
 # Parse parameters
-while getopts ":hmv:" opt; do
-  case ${opt} in
-    h )
-      help
-      exit 0
-      ;;
-    m )
-      MACSETUP=1
-      ;;
-    v )
-      VERSION=$OPTARG
-      ;;
-    \? )
-      echo "Invalid option: $OPTARG" 1>&2
-      help
-      exit 1
-      ;;
-    : )
-      echo "Invalid option: $OPTARG requires an argument" 1>&2
-      help
-      exit 1
-      ;;
-  esac
+while getopts ":hmnv:" opt; do
+    case ${opt} in
+        h )
+            help
+            exit 0
+            ;;
+        m )
+            MACSETUP=1
+            echo "Parameter -m detected"
+            ;;
+        n )
+            NEWSETUP=1
+            echo "Parameter -n detected"
+            ;;
+        v )
+            VERSION=$OPTARG
+            echo "Parameter -v detected with value $VERSION"
+            ;;
+        \? )
+            echo "Invalid option: $OPTARG" 1>&2
+            help
+            exit 1
+            ;;
+        : )
+            echo "Invalid option: $OPTARG requires an argument" 1>&2
+            help
+            exit 1
+            ;;
+    esac
 done
 
 MEM=$(docker info | grep "Total Memory" | cut -d':' -f2 | xargs | sed s/GiB//)
@@ -59,14 +65,13 @@ source env/phpfpm.env
 
 DOMAIN=${MAGENTO_DOMAIN}
 
-
 if [ -z $MACSETUP ]; then
     echo "Preparing setup installation for Linux environment and domain" "$DOMAIN"
     if [ -n "$VERSION" ]; then
         if [ "$VERSION" == "2.3.3" ]; then
-            bin/cpsample -m -v "2.3.7"  # Execute only if version is 2.3.3
+            bin/cpsample -v "2.3.7"  # Execute only if version is 2.3.3
         else
-            bin/cpsample -m -v "$VERSION"
+            bin/cpsample -v "$VERSION"
         fi
     else
       bin/cpsample
@@ -115,9 +120,15 @@ bin/check-requirements
 echo "Setting bin/magento executable permissions"
 bin/clinotty chmod u+x bin/magento
 
-echo "Importing database..."
-bin/cli mysql -h"db" -u"magento" -p"magento" --execute="DROP DATABASE magento; CREATE DATABASE magento;"
-bin/mysqlimport
+
+if [ -n "$NEWSETUP" ]; then
+    echo "Performing a new setup from scratch for domain" "$DOMAIN"
+    bin/setup-install
+else
+    echo "Importing database..."
+    bin/cli mysql -h"db" -u"magento" -p"magento" --execute="DROP DATABASE magento; CREATE DATABASE magento;"
+    bin/mysqlimport
+fi
 
 echo "Cleaning redis cache and generated files..."
 bin/redis redis-cli flushall
@@ -179,6 +190,15 @@ if [ -n "$MACSETUP" ]; then
     echo "Copying files from container to host..."
     bin/copyfromcontainer dev
     bin/copyfromcontainer pub/media
+fi
+
+if [ -n "$NEWSETUP" ]; then
+    echo "Copying app folder from container to host..."
+    bin/copyfromcontainer app
+
+    bin/clinotty cp auth.json.sample auth.json
+    bin/copyfromcontainer auth.json
+    mkdir src/dbdump
 fi
 
 echo "Setting basic URL and generating SSL certificate..."
