Refactor bin/setup: moved catalog engine setup to separate script and improved handling
- Moved the search engine configuration logic from bin/setup into a new script.
- Added improved handling for search engine settings based on env.php.dist and database.
- Enhanced user prompts and recommendations based on current and proposed configurations.
- Improved script readability and maintenance by isolating search engine setup functionality.
- Oh, and who said we can't have nice outputs in bin/mysqlimport and bin/hyva-watch? <3

diff --git a/compose/bin/mysqlimport b/compose/bin/mysqlimport
--- a/compose/bin/mysqlimport
+++ b/compose/bin/mysqlimport
@@ -1,5 +1,13 @@
 #!/usr/bin/env bash
 
+# Define text formatting
+bold=$(tput bold)
+normal=$(tput sgr0)
+green=$(tput setaf 2)
+yellow=$(tput setaf 3)
+red=$(tput setaf 1)
+blue=$(tput setaf 4)
+
 # Function to fix the SQL file by replacing the problematic collation
 fix_sql_file() {
   original_file="$1"
@@ -11,47 +19,62 @@ fix_sql_file() {
   echo "$fixed_file"
 }
 
-# List all SQL and GZ files in the dbdump directory and let the user select one
+# Function to select a file if there are multiple, or return the single file if only one exists
 select_file() {
   files=$(bin/cli find dbdump -iregex '.*\.\(sql\|gz\)')
-  if [ -z "$files" ]; then
-    echo "There are no *.sql or *.gz files in the dbdump directory"
-    exit 1
-  fi
+  file_count=$(echo "$files" | wc -w)
 
-  select file in $files; do
-    if [ -n "$file" ]; then
-      echo "$file"
-      return
-    else
-      echo "Invalid selection. Please try again."
-      exit 1
-    fi
-  done
+  if [ "$file_count" -eq 0 ]; then
+    echo "${red}${bold}Error:${normal} There are no *.sql or *.gz files in the dbdump directory."
+    exit 1
+  elif [ "$file_count" -eq 1 ]; then
+    echo "$files"  # Return the single file
+  else
+    select file in $files; do
+      if [ -n "$file" ]; then
+        echo "$file"
+        return
+      else
+        echo "${red}${bold}Invalid selection. Please try again.${normal}"
+        exit 1
+      fi
+    done
+  fi
 }
 
-echo "Please select a file to import:"
-# Main script
-if [ -z "$1" ]; then
-  path=$(select_file)
-else
-  path="$1"
-fi
-
-extension="${path##*.}"
-
+# Function to import the selected SQL file
 import_sql_file() {
   local file="$1"
   if [ "$extension" = "gz" ]; then
-    echo "Importing $file as a gzipped SQL file..."
+    echo "${blue}${bold}Importing${normal} $file as a gzipped SQL file..."
     bin/n98-magerun2 -v db:import -c gz "$file"
   else
-    echo "Importing $file as an SQL file..."
+    echo "${blue}${bold}Importing${normal} $file as an SQL file..."
     bin/n98-magerun2 -v db:import "$file"
   fi
 }
 
-echo "Selected file: $path"
+# Main script
+echo "${blue}${bold}Starting database import script...${normal}"
+
+if [ -z "$1" ]; then
+  path=$(select_file)
+else
+  path="$1"
+  echo "${yellow}${bold}File provided as argument:${normal} $path"
+fi
+
+extension="${path##*.}"
+
+echo "${blue}${bold}Selected file:${normal} $path"
 
 # Try to import the selected file and capture any errors
 import_sql_file "$path" 2>&1
+
+# Check the exit status of the import command
+if [ $? -eq 0 ]; then
+  echo "${green}${bold}Import completed successfully.${normal}"
+else
+  echo "${red}${bold}Error:${normal} Import failed. Please check the output above for details."
+  exit 1
+fi
diff --git a/compose/bin/setup b/compose/bin/setup
--- a/compose/bin/setup
+++ b/compose/bin/setup
@@ -3,16 +3,24 @@ set -o errexit
 
 start_time=$(date +%s)  # Record the start time
 
+# Define text formatting
+bold=$(tput bold)
+normal=$(tput sgr0)
+green=$(tput setaf 2)
+yellow=$(tput setaf 3)
+red=$(tput setaf 1)
+blue=$(tput setaf 4)
+
 help() {
     # Display Help
-    echo "Prepare docker setup for project."
+    echo "${bold}${blue}Prepare docker setup for project.${normal}"
     echo
     echo "Syntax: [domain (optional parameter, by default www.magento.local)] [-m] [-n]"
     echo "options:"
-    echo "h     Print this Help."
-    echo "m     Prepare environment for macOS."
-    echo "n     Perform a new setup after using bin/download to initialize ./src with a new Magento project."
-    echo "v     Specify Magento version for compose file (e.g., 2.3.3, 2.3.7, 2.4.6-php8.1, latest)"
+    echo "  ${bold}h${normal}     Print this Help."
+    echo "  ${bold}m${normal}     Prepare environment for macOS."
+    echo "  ${bold}n${normal}     Perform a new setup after using bin/download to initialize ./src with a new Magento project."
+    echo "  ${bold}v${normal}     Specify Magento version for compose file (e.g., 2.3.3, 2.3.7, 2.4.6-php8.1, latest)"
     echo
 }
 
@@ -25,23 +33,23 @@ while getopts ":hmnv:" opt; do
             ;;
         m )
             MACSETUP=1
-            echo "Parameter -m detected"
+            echo "${yellow}Parameter -m detected${normal}"
             ;;
         n )
             NEWSETUP=1
-            echo "Parameter -n detected"
+            echo "${yellow}Parameter -n detected${normal}"
             ;;
         v )
             VERSION=$OPTARG
-            echo "Parameter -v detected with value $VERSION"
+            echo "${yellow}Parameter -v detected with value ${VERSION}${normal}"
             ;;
         \? )
-            echo "Invalid option: $OPTARG" 1>&2
+            echo "${red}Invalid option: $OPTARG${normal}" 1>&2
             help
             exit 1
             ;;
         : )
-            echo "Invalid option: $OPTARG requires an argument" 1>&2
+            echo "${red}Invalid option: $OPTARG requires an argument${normal}" 1>&2
             help
             exit 1
             ;;
@@ -50,16 +58,15 @@ done
 
 MEM=$(docker info | grep "Total Memory" | cut -d':' -f2 | xargs | sed s/GiB//)
 # Docker reports RAM 0.2 less than what it is actually set to
-(( $(echo "$MEM < 5.7" | bc -l) )) && echo "There must be at least 6GB of RAM allocated to Docker to continue." && exit
+if (( $(echo "$MEM < 5.7" | bc -l) )); then
+    echo "${red}There must be at least 6GB of RAM allocated to Docker to continue.${normal}"
+    exit
+fi
 
 bin/update_phpfpm_env
 
 # shellcheck source=../env/db.env
 source env/db.env
-# shellcheck source=../env/elasticsearch.env
-source env/elasticsearch.env
-# shellcheck source=../env/opensearch.env
-source env/opensearch.env
 # shellcheck source=../env/magento.env
 source env/magento.env
 # shellcheck source=../env/rabbitmq.env
@@ -72,7 +79,7 @@ DOMAIN=${MAGENTO_DOMAIN}
 bin/stopall
 
 if [ -z $MACSETUP ]; then
-    echo "Preparing setup installation for Linux environment and domain" "$DOMAIN"
+    echo "${green}Preparing setup installation for Linux environment and domain ${DOMAIN}${normal}"
     if [ -n "$VERSION" ]; then
         if [ "$VERSION" == "2.3.3" ]; then
             bin/cpsample -v "2.3.7"  # Execute only if version is 2.3.3
@@ -80,10 +87,10 @@ if [ -z $MACSETUP ]; then
             bin/cpsample -v "$VERSION"
         fi
     else
-      bin/cpsample
+        bin/cpsample
     fi
 else
-    echo "Preparing setup installation for macOS environment and domain" "$DOMAIN"
+    echo "${green}Preparing setup installation for macOS environment and domain ${DOMAIN}${normal}"
     if [ -n "$VERSION" ]; then
         if [ "$VERSION" == "2.3.3" ]; then
             bin/cpsample -m -v "2.3.7"  # Execute only if version is 2.3.3
@@ -91,56 +98,61 @@ else
             bin/cpsample -m -v "$VERSION"
         fi
     else
-      bin/cpsample -m
+        bin/cpsample -m
     fi
 fi
 
 bin/start --no-dev
 # Check the exit status of the start script
-[ $? != 0 ] && echo "Failed to start Docker services" && exit
+if [ $? != 0 ]; then
+    echo "${red}Failed to start Docker services${normal}"
+    exit
+fi
 
 # Check if auth.json exists to avoid Composer authentication errors
 bin/setup-composer-auth
 
 bin/check-broken-symlinks
 # Check the exit status of the check-broken-symlinks script
-[ $? != 0 ] && echo "Aborting script due to broken symlinks." && exit 1
+if [ $? != 0 ]; then
+    echo "${red}Aborting script due to broken symlinks.${normal}"
+    exit 1
+fi
 
-echo "Copying project files to container..."
+echo "${blue}Copying project files to container...${normal}"
 bin/copytocontainer --all
 
-echo "Adding Magento modules to Composer allow-plugins directive..."
+echo "${blue}Adding Magento modules to Composer allow-plugins directive...${normal}"
 bin/clinotty composer config --no-plugins allow-plugins.magento/magento-composer-installer true
 bin/clinotty composer config --no-plugins allow-plugins.magento/inventory-composer-installer true
 bin/clinotty composer config --no-plugins allow-plugins.laminas/laminas-dependency-plugin true
 
-echo "Installing composer modules..."
+echo "${blue}Installing composer modules...${normal}"
 bin/composer install --ignore-platform-reqs
-
 
 if [ "$VERSION" == "2.3.3" ] || [ "$VERSION" == "2.3.7" ]; then
     # Wait for user input
-    echo "Composer install completed."
-    echo "Please fix the xdebug bug by editing the vendor/magento/magento2-functional-testing-framework/src/Magento/FunctionalTestingFramework/_bootstrap.php"
-    echo "You can find the fix on: https://tinyurl.com/mrdr4jn"
+    echo "${green}Composer install completed.${normal}"
+    echo "${yellow}Please fix the xdebug bug by editing the vendor/magento/magento2-functional-testing-framework/src/Magento/FunctionalTestingFramework/_bootstrap.php${normal}"
+    echo "${yellow}You can find the fix on: https://tinyurl.com/mrdr4jn${normal}"
     bin/fix_xdebug
 fi
 
 bin/check-requirements
 
-echo "Setting bin/magento executable permissions"
+echo "${blue}Setting bin/magento executable permissions${normal}"
 bin/clinotty chmod u+x bin/magento
 
 if [ -n "$NEWSETUP" ]; then
-    echo "Performing a new setup from scratch for domain" "$DOMAIN"
+    echo "${green}Performing a new setup from scratch for domain ${DOMAIN}${normal}"
     bin/setup-install
 else
-    echo "Importing database..."
+    echo "${blue}Importing database...${normal}"
     bin/cli mysql -h"db" -u"magento" -p"magento" --execute="DROP DATABASE magento; CREATE DATABASE magento;"
     bin/mysqlimport
 fi
 
-echo "Cleaning redis cache and generated files..."
+echo "${blue}Cleaning redis cache and generated files...${normal}"
 bin/redis redis-cli flushall
 bin/clinotty rm -rf generated
 bin/clinotty rm -rf var/*
@@ -148,63 +160,45 @@ bin/clinotty rm -rf var/*
 if [ -z $MACSETUP ]; then
     if [ -n "$VERSION" ]; then
         if [ "$VERSION" == "2.3.3" ]; then
-            echo "Reverting docker configuration to PHP 7.3 after composer:install has finished to avoid setup:di:compile errors"
+            echo "${yellow}Reverting docker configuration to PHP 7.3 after composer:install has finished to avoid setup:di:compile errors${normal}"
             bin/cpsample -v "2.3.3"
 
             bin/stop
             bin/start --no-dev
-            [ $? != 0 ] && echo "Failed to start Docker services" && exit
+            if [ $? != 0 ]; then
+                echo "${red}Failed to start Docker services${normal}"
+                exit
+            fi
         fi
     fi
 else
     if [ -n "$VERSION" ]; then
         if [ "$VERSION" == "2.3.3" ]; then
-            echo "Reverting docker configuration to PHP 7.3 after composer:install has finished to avoid setup:di:compile errors"
+            echo "${yellow}Reverting docker configuration to PHP 7.3 after composer:install has finished to avoid setup:di:compile errors${normal}"
             bin/cpsample -m -v "2.3.3"
 
             bin/stop
             bin/start --no-dev
-            [ $? != 0 ] && echo "Failed to start Docker services" && exit
+            if [ $? != 0 ]; then
+                echo "${red}Failed to start Docker services${normal}"
+                exit
+            fi
         fi
     fi
 fi
 
-echo "Running magento set:up..."
+echo "${blue}Running magento set:up...${normal}"
 bin/clinotty bin/magento setup:up
 
-# Ask user to choose between Elasticsearch and ElasticSuite
-echo "Choose the search engine to configure:"
-echo "1) Elasticsearch"
-echo "2) ElasticSuite"
-read -p "Enter the number of your choice: " search_engine_choice
-
-if [ "$search_engine_choice" == "1" ]; then
-    echo "Setting up Elasticsearch.. to host ${ES_HOST} and port ${ES_PORT}.."
-     bin/clinotty bin/magento config:set catalog/search/elasticsearch7_server_hostname "${ES_HOST}"
-     bin/clinotty bin/magento config:set catalog/search/elasticsearch7_server_port "${ES_PORT}"
-     bin/clinotty bin/magento config:set catalog/search/engine "${ES_VERSION}"
-    echo "Elasticsearch configuration completed."
-elif [ "$search_engine_choice" == "2" ]; then
-    echo "Setting up ElasticSuite..."
-     bin/clinotty bin/magento config:set smile_elasticsuite_core_base_settings/es_client/servers "${ES_HOST}:${ES_PORT}"
-     bin/clinotty bin/magento config:set smile_elasticsuite_core_base_settings/es_client/enable_https_mode '0'
-     bin/clinotty bin/magento config:set smile_elasticsuite_core_base_settings/es_client/enable_http_auth '0'
-     bin/clinotty bin/magento config:set smile_elasticsuite_core_base_settings/es_client/http_auth_user ''
-     bin/clinotty bin/magento config:set smile_elasticsuite_core_base_settings/es_client/http_auth_pwd ''
-     bin/clinotty bin/magento config:set catalog/search/engine "${ELASTICSUITE}"
-    echo "ElasticSuite configuration completed."
-else
-    echo "Invalid choice. Exiting."
-    exit 1
-fi
+bin/setup-search-engine
 
 #echo "Running magento app:config:import..."
 #bin/clinotty bin/magento app:config:import
 
-echo "Creating admin user ${MAGENTO_ADMIN_USER} with password ${MAGENTO_ADMIN_PASSWORD}..."
+echo "${blue}Creating admin user ${MAGENTO_ADMIN_USER} with password ${MAGENTO_ADMIN_PASSWORD}.${normal}"
 bin/clinotty bin/magento admin:user:create --admin-user="$MAGENTO_ADMIN_USER" --admin-password="$MAGENTO_ADMIN_PASSWORD" --admin-email="$MAGENTO_ADMIN_EMAIL" --admin-firstname="$MAGENTO_ADMIN_FIRST_NAME" --admin-lastname="$MAGENTO_ADMIN_LAST_NAME"
 
-echo "Forcing deploy of static content to speed up initial requests..."
+echo "${blue}Forcing deploy of static content to speed up initial requests.${normal}"
 bin/clinotty bin/magento setup:static-content:deploy -f
 
 if [ -n "$MACSETUP" ]; then
@@ -215,13 +209,13 @@ fi
 bin/create_phpstan_files
 
 if [ -n "$MACSETUP" ]; then
-    echo "Copying files from container to host..."
+    echo "${blue}Copying files from container to host.${normal}"
     bin/copyfromcontainer dev
     bin/copyfromcontainer pub/media
 fi
 
 if [ -n "$NEWSETUP" ]; then
-    echo "Copying app folder from container to host..."
+    echo "${blue}Copying app folder from container to host.${normal}"
     bin/copyfromcontainer app
 
     bin/clinotty cp auth.json.sample auth.json
@@ -229,29 +223,29 @@ if [ -n "$NEWSETUP" ]; then
     mkdir src/dbdump
 fi
 
-echo "Setting basic URL and generating SSL certificate..."
+echo "${blue}Setting basic URL and generating SSL certificate.${normal}"
 bin/setup-domain "${DOMAIN}"
 
-echo "Re-indexing with selected search engine..."
+echo "${blue}Re-indexing with selected search engine.${normal}"
 bin/clinotty bin/magento indexer:reindex
 
-echo "Clearing the cache to apply updates..."
+echo "${blue}Clearing the cache to apply updates.${normal}"
 bin/clinotty bin/magento cache:flush
 
-echo "Installing cron, run 'bin/cron start' to enable..."
+echo "${blue}Installing cron, run ‘bin/cron start’ to enable${normal}"
 bin/clinotty bin/magento cron:install
 
-echo "Turning on developer mode..."
+echo "${blue}Turning on developer mode.${normal}"
 bin/clinotty bin/magento deploy:mode:set developer
 
 if [ -n "$MACSETUP" ]; then
-    echo "Copying files from container to host..."
+    echo "${blue}Copying files from container to host.${normal}"
     bin/copyfromcontainer vendor
     bin/copyfromcontainer generated
 fi
 
-echo "Docker development environment setup complete."
-echo "You may now access your Magento instance at https://${DOMAIN}/"
+echo "${green}Docker development environment setup complete.${normal}"
+echo "${green}You may now access your Magento instance at https://${DOMAIN}/${normal}"
 
 end_time=$(date +%s)
 elapsed_seconds=$(( end_time - start_time ))
@@ -260,4 +254,4 @@ elapsed_seconds=$(( end_time - start_time ))
 elapsed_minutes=$(( elapsed_seconds / 60 ))
 remaining_seconds=$(( elapsed_seconds % 60 ))
 
-echo "Total execution time: ${elapsed_minutes} minute(s) and ${remaining_seconds} second(s)"
+echo "${blue}Total execution time: ${elapsed_minutes} minute(s) and ${remaining_seconds} second(s)${normal}"
